---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubeclarity
  namespace: apps-system
spec:
  interval: 24h
  url: https://openclarity.github.io/kubeclarity
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeclarity
  namespace: apps-system
spec:
  interval: 30m
  timeout: 5m # timeout for kubernetes operations (default 5m)
  install:
    remediation:
      retries: -1 # always try to fix
  chart:
    spec:
      chart: kubeclarity
      version: "*" # use latest version
      sourceRef:
        kind: HelmRepository
        name: kubeclarity
        namespace: apps-system
      interval: 12h
  values:
    kubeclarity-postgresql:
      enabled: false
    kubeclarity-postgresql-external:
      enabled: true
      auth:
        existingSecret: kubeclarity-postgresql-secret
        username: kubeclarity
        host: vmalmapsql.home  # replace this to reach your PostgreSQL instance
        port: 5432
        database: kubeclarity
        sslMode: disable
    # PostgreSQL connection information
    kubeclarity-postgresql-secret:
      # Set create to true if you want this helm chart to create a secret holding pgsql password
      # based on global.databasePassword value
      # If create is set to false, a secret should already exist which has PostgreSQL
      # password under secretKey key
      create: true
      secretKey: "kubeclarity"
    service:
      type: ClusterIP
      port: 8080
      annotations: {}
    ingress:
      enabled: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeclarity-ingress
  namespace: apps-system
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "wss"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    secretName: kubec-host-secret-tls
  rules:
  - host: kubeclarity.home
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: kubeclarity-kubeclarity
              port:
                number: 8080