apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# patch the release version
# * = latest release
# <2.0.0 = release lower than 2.0.0
# 2.7.x = latest subversion in release 2.7
# =2.7.0 = fixed release 2.7.0
patches:
- target:
    kind: HelmRelease
    name: awx-operator
    namespace: awx-system
  patch: |-
    - op: replace
      path: /spec/chart/spec/version
      value: "*"

resources:
  - awx-ns.yaml
  - awx-operator.yaml