---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: infra-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: infra-system
spec:
  interval: 30m
  timeout: 5m # timeout for kubernetes operations (default 5m)
  install:
    remediation:
      retries: -1 # always try to fix
  chart:
    spec:
      chart: metrics-server
      version: "*" # latest version
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: infra-system
      interval: 12h
  values:
    apiService.insecureSkipTLSVerify: true
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP