---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: infra-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx # https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: infra-system
spec:
  interval: 30m
  timeout: 5m # timeout for kubernetes operations (default 5m)
  install:
    remediation:
      retries: -1 # always try to fix
  chart:
    spec:
      chart: ingress-nginx
      version: "*" # latest version
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: infra-system
      interval: 12h