---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-volume
  namespace: awx-system
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: awx-projects-volume
  hostPath:
    path: /data/projects