---
apiVersion: v1
kind: Namespace
metadata:
  name: core-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flannel
  namespace: core-system
spec:
  interval: 24h
  url: https://flannel-io.github.io/flannel/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1 # always helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease # always HelmRelease
metadata:
  name: flannel # name in kubernetes
  namespace: core-system # namespace in kubernetes
spec:
  interval: 30m # check for updates
  timeout: 5m # timeout for kubernetes operations (default 5m)
  install:
    remediation:
      retries: -1 # always try to fix
  releaseName: flannel # best use upstream chart name
  chart:
    spec:
      chart: flannel  # Must be the same as the upstream chart name
      version: '*' # use latest version
      interval: 12h
      sourceRef:
        kind: HelmRepository # <HelmRepository|GitRepository|Bucket>
        name: flannel # References the HelmRepository usually upstream chart name
        namespace: core-system