---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: core-system
spec:
  addresses:
  - 10.0.2.100-10.0.2.110
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: core-system
spec:
  ipAddressPools:
  - default